/**
 * Disables Xcode's user script sandboxing for the iOS project.
 *
 * Xcode 16 defaults ENABLE_USER_SCRIPT_SANDBOXING to YES. React Native's
 * "Bundle React Native code and images" phase writes into the built .app --
 * for dev client builds it writes ip.txt, the address of the Metro server --
 * and the sandbox denies it:
 *
 *   error: Sandbox: bash deny(1) file-write-data .../healthvismobile.app/ip.txt
 *
 * ios/ is gitignored and regenerated by prebuild, so setting this by hand in
 * the pbxproj is lost on the next `expo prebuild --clean`. This plugin applies
 * it every time the project is generated.
 */

const { withXcodeProject } = require("@expo/config-plugins");

const withScriptSandboxDisabled = (config) =>
  withXcodeProject(config, (modConfig) => {
    const project = modConfig.modResults;
    const configurations = project.pbxXCBuildConfigurationSection();

    for (const key of Object.keys(configurations)) {
      const buildSettings = configurations[key]?.buildSettings;
      // Comment entries in this section have no buildSettings; skip them.
      if (!buildSettings) continue;
      buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = "NO";
    }

    return modConfig;
  });

module.exports = withScriptSandboxDisabled;
